from decentai.losses.loss_calculator import *
from decentai.losses.categorical_cross_entropy_loss import CategoricalCrossEntropyLoss
from decentai.losses.mean_squared_error_loss import MeanSquaredErrorLoss
