from decentai.utils.loader_factory import get_data_loader
from decentai.utils.base_loader import GenericDataLoader
from decentai.utils.mnist_loader import MNISTDataLoader
from decentai.utils.cifar10_loader import CIFAR10DataLoader